### ISSUE TITLE
Listing posts does not work

### ISSUE THREAD

**Issue by torokmark** [arjkb/basics#3]
**Description**:   
I would like to use your theme, but facing that list of posts does not 
seem to show up. Everything else works as expected.

As a blogger/user I want to see list of posts   
when I create one or more posts in the content/posts folder by using `hugo new posts/my-post.md'

**Reproduction**:   
Create a simple blog from scratch following https://gohugo.io/getting-started/quick-start/
    
Listing works with other themes as expected.

**Comment by arjkb** [comment]
Hi @torokmark,

I think the issue here is that you're using `posts/`.  

Try renaming that folder to `post/` instead and see if the problem persists.

**Comment by torokmark** [comment]
Thank you so much!

It works as charm!
